# Generated by Django 4.2.17 on 2025-03-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='bannerimage',
            field=models.ImageField(default='blog/default2.jpg', upload_to='blog/'),
        ),
    ]
